FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY portal_portal/pom.xml .
COPY portal_portal/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
dear is shre